name: profile_ui
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.0.2+1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/images/
   - assets/on_boarding_images/
   - assets/logos/
